export const FILTER = "FILTER"
export const ADD_FAV = "ADD_FAV"
export const REMOVE_FAV = "REMOVE_FAV"
export const ACCESS_TRUE = "ACCESS_TRUE"
export const ACCESS_FALSE = "ACCESS_FALSE"
export const ORDER = "ORDER"